In [1]:
import tensorflow as tf

In [3]:
from tensorflow.keras.models import Model

In [4]:
from tensorflow.keras.layers import Input, Flatten, Dense

### Functional Model

In [14]:
ip = Input(shape = (1024,1024))

In [15]:
flat = Flatten()(ip)

In [16]:
den1 = Dense(1024, activation = "relu")(flat)

In [17]:
den2 = Dense(512, activation = "relu")(den1)

In [18]:
den3 = Dense(1000, activation = "relu")(den2)

In [19]:
out = Dense(10, activation = "softmax")(den3)

In [20]:
fmodel = Model(inputs = ip, outputs = out)

In [21]:
fmodel.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 1024, 1024)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 1048576)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1024)                │   1,073,742,848 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 512)                 │         524,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1000)                │         513,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 10)                  │          10,010 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,074,790,658 (4.00 GB)

 Trainable params: 1,074,790,658 (4.00 GB)

 Non-trainable params: 0 (0.00 B)

In [13]:
fmodel.compile(
                optimizer = "adam",
                loss = "sparse_categorical_crossentropy",
                metrics = ["accuracy"]
    
                    )

In [ ]:
fmodel.fit(X_train, y_train, epochs = 15)

### Tensorflow

In [27]:
import numpy as np

In [22]:
import tensorflow as tf

In [23]:
t1 = tf.constant([10,20,30,40,50])

In [24]:
t1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50], dtype=int32)>

In [25]:
type(t1)

tensorflow.python.framework.ops.EagerTensor

In [26]:
print(type(t1))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [32]:
ary = np.arange(10, 22, 1)

In [33]:
ary

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [34]:
ary.size

12

In [36]:
tf.constant(ary, shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])>

In [37]:
tf.zeros((4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>