In [1]:
import cv2

In [2]:
horse = cv2.imread(r"C:\Users\Hello\Desktop\horse.jpg")

In [3]:
horse

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [4]:
cv2.imshow("horse image", horse)
cv2.waitKey(-1)

-1

In [5]:
import numpy as np

In [6]:
np.zeros((512,512))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(512, 512))

In [7]:
z1=np.zeros((512,512))

In [8]:
z1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(512, 512))

In [9]:
cv2.imshow("horse image", z1)
cv2.waitKey(0)

-1

In [10]:
img2=np.ones((512,512))

In [11]:
img2

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(512, 512))

In [12]:
cv2.imshow("horse image", img2)
cv2.waitKey(1)

-1

### resize

In [13]:
horse

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [14]:
cv2.imshow("black_image",z1)
cv2.imshow("white_image",img2)
cv2.waitKey(-1)

-1

In [15]:
horse.shape

(148, 210, 3)

In [16]:
cv2.imshow("horse image",horse)
cv2.waitKey(-1)

-1

In [17]:
hor=cv2.resize(horse,(200,300))

In [18]:
hor

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [19]:
cv2.imshow("small image",hor)
cv2.waitKey(-1)

-1

In [20]:
cv2.imshow("horse image",horse)
cv2.imshow("small image",hor)
cv2.waitKey(-1)

-1

In [21]:
cv2.imwrite("small_image.jpg",hor)

True

### FRUIT

In [22]:
fruit=cv2.imread(r"C:\Users\Hello\Downloads\ChatGPT Image Jun 4, 2026, 11_42_14 AM.png")

In [23]:
fruit

array([[[235, 232, 227],
        [238, 235, 231],
        [239, 236, 231],
        ...,
        [164, 168, 169],
        [163, 167, 170],
        [162, 167, 168]],

       [[237, 234, 229],
        [237, 234, 229],
        [239, 236, 230],
        ...,
        [163, 167, 168],
        [163, 167, 168],
        [163, 167, 168]],

       [[238, 235, 230],
        [237, 235, 229],
        [238, 236, 230],
        ...,
        [163, 166, 166],
        [163, 166, 167],
        [164, 167, 168]],

       ...,

       [[178, 175, 186],
        [191, 187, 197],
        [159, 152, 166],
        ...,
        [ 36,  54,  82],
        [ 53,  83, 114],
        [ 41,  70, 102]],

       [[175, 174, 186],
        [187, 187, 195],
        [163, 160, 172],
        ...,
        [ 35,  53,  79],
        [ 58,  89, 117],
        [ 47,  77, 109]],

       [[169, 168, 181],
        [174, 172, 185],
        [169, 167, 179],
        ...,
        [ 40,  59,  84],
        [ 51,  71, 101],
        [ 55,  79, 108]]

In [24]:
fruit.shape

(1086, 1448, 3)

In [25]:
cv2.imshow("fruit image", fruit)
cv2.waitKey(-1)

-1

In [26]:
fru=cv2.resize(fruit,(200,300))

In [27]:
fru

array([[[239, 237, 231],
        [243, 241, 238],
        [245, 243, 240],
        ...,
        [164, 167, 168],
        [164, 166, 166],
        [164, 167, 168]],

       [[239, 236, 231],
        [242, 241, 237],
        [244, 243, 240],
        ...,
        [163, 167, 168],
        [164, 167, 168],
        [165, 167, 168]],

       [[239, 236, 231],
        [242, 241, 237],
        [244, 243, 240],
        ...,
        [163, 167, 167],
        [163, 166, 167],
        [165, 167, 168]],

       ...,

       [[167, 163, 174],
        [177, 179, 187],
        [185, 188, 198],
        ...,
        [ 40,  59,  80],
        [ 37,  60,  86],
        [ 44,  67,  93]],

       [[179, 178, 193],
        [163, 161, 173],
        [152, 155, 176],
        ...,
        [ 46,  65,  89],
        [ 52,  76, 101],
        [ 51,  77, 105]],

       [[172, 170, 182],
        [169, 171, 184],
        [164, 170, 187],
        ...,
        [ 53,  78, 104],
        [ 45,  71, 100],
        [ 37,  55,  78]]

In [28]:
cv2.imshow("fruit",fru)
cv2.waitKey(-1)

-1

### IMAGE FLIP

In [29]:
fru_0=cv2.flip(fru,0)

In [30]:
fru_0

array([[[172, 170, 182],
        [169, 171, 184],
        [164, 170, 187],
        ...,
        [ 53,  78, 104],
        [ 45,  71, 100],
        [ 37,  55,  78]],

       [[179, 178, 193],
        [163, 161, 173],
        [152, 155, 176],
        ...,
        [ 46,  65,  89],
        [ 52,  76, 101],
        [ 51,  77, 105]],

       [[167, 163, 174],
        [177, 179, 187],
        [185, 188, 198],
        ...,
        [ 40,  59,  80],
        [ 37,  60,  86],
        [ 44,  67,  93]],

       ...,

       [[239, 236, 231],
        [242, 241, 237],
        [244, 243, 240],
        ...,
        [163, 167, 167],
        [163, 166, 167],
        [165, 167, 168]],

       [[239, 236, 231],
        [242, 241, 237],
        [244, 243, 240],
        ...,
        [163, 167, 168],
        [164, 167, 168],
        [165, 167, 168]],

       [[239, 237, 231],
        [243, 241, 238],
        [245, 243, 240],
        ...,
        [164, 167, 168],
        [164, 166, 166],
        [164, 167, 168]]

In [31]:
cv2.imshow("fruit_0",fru_0)
cv2.waitKey(-1)

-1

In [32]:
cv2.imshow("fruit",fru)
cv2.imshow("fruit_flip0",fru_0)
cv2.waitKey(-1)

-1

### SIDE FLIP

In [33]:
fru_1=cv2.flip(fru,1)

In [34]:
cv2.imshow("fruit_1",fru_1)
cv2.waitKey(-1)

-1

In [35]:
cv2.imshow("fruit",fru)
cv2.imshow("fruit_flip0",fru_0)
cv2.imshow("fruit_flip1",fru_1)
cv2.waitKey(-1)

-1

###     mkj

In [36]:
fru=cv2.resize(fru,(300,350))

In [37]:
fru

array([[[239, 237, 231],
        [241, 239, 234],
        [243, 241, 238],
        ...,
        [164, 166, 166],
        [164, 166, 167],
        [164, 167, 168]],

       [[239, 236, 231],
        [240, 238, 234],
        [242, 241, 238],
        ...,
        [164, 167, 167],
        [164, 167, 168],
        [165, 167, 168]],

       [[239, 236, 231],
        [240, 238, 234],
        [242, 241, 237],
        ...,
        [163, 166, 167],
        [164, 167, 167],
        [165, 167, 168]],

       ...,

       [[171, 168, 181],
        [172, 170, 181],
        [172, 173, 183],
        ...,
        [ 42,  65,  90],
        [ 44,  68,  94],
        [ 46,  70,  97]],

       [[177, 176, 191],
        [171, 170, 183],
        [163, 162, 176],
        ...,
        [ 50,  74,  99],
        [ 49,  74, 100],
        [ 48,  72,  99]],

       [[172, 170, 182],
        [170, 170, 183],
        [168, 171, 184],
        ...,
        [ 46,  72, 100],
        [ 41,  63,  89],
        [ 37,  55,  78]]

In [38]:
cv2.imshow("fru image",fru)
cv2.waitKey(-1)

-1

In [39]:
fru=cv2.flip(fru,-1)

In [40]:
fru

array([[[ 37,  55,  78],
        [ 41,  63,  89],
        [ 46,  72, 100],
        ...,
        [168, 171, 184],
        [170, 170, 183],
        [172, 170, 182]],

       [[ 48,  72,  99],
        [ 49,  74, 100],
        [ 50,  74,  99],
        ...,
        [163, 162, 176],
        [171, 170, 183],
        [177, 176, 191]],

       [[ 46,  70,  97],
        [ 44,  68,  94],
        [ 42,  65,  90],
        ...,
        [172, 173, 183],
        [172, 170, 181],
        [171, 168, 181]],

       ...,

       [[165, 167, 168],
        [164, 167, 167],
        [163, 166, 167],
        ...,
        [242, 241, 237],
        [240, 238, 234],
        [239, 236, 231]],

       [[165, 167, 168],
        [164, 167, 168],
        [164, 167, 167],
        ...,
        [242, 241, 238],
        [240, 238, 234],
        [239, 236, 231]],

       [[164, 167, 168],
        [164, 166, 167],
        [164, 166, 166],
        ...,
        [243, 241, 238],
        [241, 239, 234],
        [239, 237, 231]]

In [41]:
cv2.imshow("fru image",fru)
cv2.imshow("flip_fru",fru_1)
cv2.waitKey(-1)

-1

In [42]:
fru

array([[[ 37,  55,  78],
        [ 41,  63,  89],
        [ 46,  72, 100],
        ...,
        [168, 171, 184],
        [170, 170, 183],
        [172, 170, 182]],

       [[ 48,  72,  99],
        [ 49,  74, 100],
        [ 50,  74,  99],
        ...,
        [163, 162, 176],
        [171, 170, 183],
        [177, 176, 191]],

       [[ 46,  70,  97],
        [ 44,  68,  94],
        [ 42,  65,  90],
        ...,
        [172, 173, 183],
        [172, 170, 181],
        [171, 168, 181]],

       ...,

       [[165, 167, 168],
        [164, 167, 167],
        [163, 166, 167],
        ...,
        [242, 241, 237],
        [240, 238, 234],
        [239, 236, 231]],

       [[165, 167, 168],
        [164, 167, 168],
        [164, 167, 167],
        ...,
        [242, 241, 238],
        [240, 238, 234],
        [239, 236, 231]],

       [[164, 167, 168],
        [164, 166, 167],
        [164, 166, 166],
        ...,
        [243, 241, 238],
        [241, 239, 234],
        [239, 237, 231]]

### CHANGE COLOR

In [54]:
fruit_grey=cv2.cvtColor(fruit,cv2.COLOR_BGR2GRAY)

In [55]:
fruit_grey.shape

(1086, 1448)

In [56]:
fruit.shape

(1086, 1448, 3)

In [57]:
cv2.imshow("fruit_grey",fruit_grey)
cv2.waitKey(-1)

-1

In [52]:
fruit.shape

(1086, 1448, 3)

In [53]:
fru.shape

(350, 300, 3)

In [58]:
# [:,:,0]=red
#[:,:,1]=green
#[:,:,2]=blue

In [59]:
fru_7=fru.copy()
fru_8=fru.copy()
fru_9=fru.copy()

In [60]:
fru_7[:,:,0]=0

In [61]:
cv2.imshow("fru_7",fru_7)
cv2.waitKey(-1)

-1

In [62]:
fru_8[:,:,1]=0

In [64]:
cv2.imshow("fru_8",fru_8)
cv2.waitKey(-1)

-1

In [65]:
fru_9[:,:,2]=0

In [66]:
cv2.imshow("fru_9",fru_9)
cv2.waitKey(-1)

-1